#
# Makefile for CMPS 356
# Lab 1: Introduction to Prolog and expert systems
# This makefile does not compile anything, it is a wrapper for
# Prolog so you do not have to manually 'consult' a file every
# time.
#
# Note that it also uses swipl, which might be a bit different
# from gprolog
#
INPUTFILE=lab1.pl

consult: 
	swipl $(INPUTFILE) 
