#CMPS 3500 
#ErikSoto
#Lab04 - Introduction to Java


all: 
	javac Erik_Soto_Coin.java
	javac Erik_Soto_Compute.java
	javac Erik_Soto_Lab04.java 

clean:
	rm Erik_Soto_Coin.class
	rm Erik_Soto_Compute.class 
	rm Erik_Soto_Lab04.class
