all: if for returnfunction void while

if: if.cpp
	g++ -o if if.cpp

for: for.cpp
	g++ -o for for.cpp

returnfunction: returnfunction.cpp
	g++ -o returnfunction returnfunction.cpp

void: void.cpp
	g++ -o void void.cpp

while: while.cpp
	g++ -o while while.cpp

clean: 
	rm if for returnfunction void while
